parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: symfony
    database_user: root
    database_password: '1234'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: a7fe474632016d7a09d70d4bcdaab1fab6d4b55a
    database_path: null
    blogger_blog.comments.latest_comment_limit: 10    

